### ISSUE TITLE
ubuntu:xenial apt-get update is broken on several architectures

### ISSUE THREAD

**Issue by vielmetti** [tianon/jenkins-groovy#24] opened 2017-04-06 19:23 UTC
Problem: the armhf/ubuntu:xenial and aarch64/ubuntu:xenial images are broken, in the sense that when you run `apt-get update` in each, they fail to load.

A gist that shows these is here:

https://gist.github.com/vielmetti/60e44d861330bb52d8d2ac40d2d787e2

What I expected: `apt-get update` in `aarch64/ubuntu:xenial` works.

What I got: see log file above, the specific lines are

```
Err:6 http://security.ubuntu.com/ubuntu xenial-security/main arm64 Packages
  404  Not Found [IP: 91.189.88.152 80]
```

Root cause: this Ubuntu bug

https://bugs.launchpad.net/ubuntu/+source/livecd-rootfs/+bug/1679252

Suggested fixes:

1. Test the suggested fix by using the -proposed channel for xenial to build an image to test
2. Put in a temporary fix by using an older build?

Repeat by:

Use the multiarch support in Docker for Mac if you don't have physical hardware, then run

```shell
% docker run --rm aarch64/ubuntu:xenial apt-get update
% docker run --rm armhf/ubuntu:xenial apt-get update
```

**Comment by yosifkit** [comment] 2017-04-07 17:25
Closing as duplicate of #23 and tracked in https://github.com/docker-library/official-images/issues/2804.

**Closed as completed by yosifkit** 2017-04-07 17:25 UTC
